### ISSUE TITLE
Question: Why does this Addon need to read the browser history?

### ISSUE THREAD

**Issue by ncri** [yggdrasil-group/Hide-Most-Visited-Pages-Reloaded#6]
Great Addon by the way. ;-)

**Comment by peadarDoyle** [comment]
Not associated with this repo but was snooping around the code for much the same reason. It looks like the extension uses a single call to the `chrome.webNavigation` api which causes this warning to appear.

As you can see all this api call does is check for the DOM to be loaded.

```
chrome.webNavigation.onDOMContentLoaded.addListener ( event ) ->
  onDOMContentLoaded()
  return

```
Albeit the following check for a DOM load is also included and does the same thing.

```
document.addEventListener 'DOMContentLoaded', ( event ) ->
  onDOMContentLoaded()
  return

```

Hopefully one of the contributors can clarify why the `chrome.webNavigation` call is necessary - I'm assuming there is an edge case where the document event listener doesn't fire. If not, it looks like the webNavigation access permission can be removed which should remove the scary "read the browser history" message when installing the extension.

**Comment by ncri** [comment]
Thanks for checking the code peadarDoyle, I was assuming something like this.

**Comment by ysragh** [comment]
The code is run in the background page and a call to `document` in the background page refers to the background page itself, so it would kick in when the background page has been loaded, but we want it to run for the chrome://newtab page, so we have to register a handler via `chrome.webNavigation.onDOMContentLoaded.addListener`. I'm sorry, it's bull, but I can't change that :(

**Comment by ncri** [comment]
Thanks for the explanation, makes sense.
