### ISSUE TITLE
Doesn't work anymore since Chrome 57

### ISSUE THREAD

**Issue by MarkTiedemann** [yggdrasil-group/Hide-Most-Visited-Pages-Reloaded#8]
See title.

**Comment by ysragh** [comment]
It works in Chromium Version 58.0.3029.81 (64-bit) and Chrome Version 58.0.3029.81 (64-bit).

If it does not work for you, try removing your profile (make sure everything is synced, so you don't have to customize Chrome again; before removing your profile). Here's a short video on how to remove your Chrome userprofile: https://ygg.li/chrome-remove-profile

Then simply add your account again and wait for it to sync. Shut down Chrome. Start Chrome and see if it's still not working.

Sometimes corrupted profiles seem to cause this issue.

**Comment by MarkTiedemann** [comment]
After resetting my profile, it works again. Thanks a lot, @ysragh! :)
